[2024-08-05T00:00:57.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T00:00:57.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:00:19.634528+00:00 [queued]>
[2024-08-05T00:00:57.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:00:19.634528+00:00 [queued]>
[2024-08-05T00:00:57.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T00:00:57.141+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_fatoemailmarketing> on 2024-08-05 00:00:19.634528+00:00
[2024-08-05T00:00:57.154+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3718) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T00:00:57.156+0000] {standard_task_runner.py:64} INFO - Started process 3720 to run task
[2024-08-05T00:00:57.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_fatoemailmarketing', 'manual__2024-08-05T00:00:19.634528+00:00', '--job-id', '1475', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp675ycb7g']
[2024-08-05T00:00:57.158+0000] {standard_task_runner.py:91} INFO - Job 1475: Subtask carga_fatoemailmarketing
[2024-08-05T00:00:57.194+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:00:19.634528+00:00 [running]> on host 88edf8e2824b
[2024-08-05T00:00:57.243+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_fatoemailmarketing' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T00:00:19.634528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T00:00:19.634528+00:00'
[2024-08-05T00:00:57.244+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T00:00:57.304+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T00:00:57.333+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T00:00:57.334+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T00:00:57.342+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_fatoemailmarketing, run_id=manual__2024-08-05T00:00:19.634528+00:00, execution_date=20240805T000019, start_date=20240805T000057, end_date=20240805T000057
[2024-08-05T00:00:57.378+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T00:00:57.390+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T00:00:57.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
