[2024-08-04T19:45:17.531+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T19:45:17.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.Carga_Dimensao_user_type manual__2024-08-04T19:44:58.390721+00:00 [queued]>
[2024-08-04T19:45:17.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.Carga_Dimensao_user_type manual__2024-08-04T19:44:58.390721+00:00 [queued]>
[2024-08-04T19:45:17.557+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T19:45:17.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Carga_Dimensao_user_type> on 2024-08-04 19:44:58.390721+00:00
[2024-08-04T19:45:17.577+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1560) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T19:45:17.579+0000] {standard_task_runner.py:64} INFO - Started process 1562 to run task
[2024-08-04T19:45:17.579+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'Carga_Dimensao_user_type', 'manual__2024-08-04T19:44:58.390721+00:00', '--job-id', '851', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpyn3kfrjx']
[2024-08-04T19:45:17.580+0000] {standard_task_runner.py:91} INFO - Job 851: Subtask Carga_Dimensao_user_type
[2024-08-04T19:45:17.634+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.Carga_Dimensao_user_type manual__2024-08-04T19:44:58.390721+00:00 [running]> on host 83ccd21ce624
[2024-08-04T19:45:17.689+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='Carga_Dimensao_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T19:44:58.390721+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T19:44:58.390721+00:00'
[2024-08-04T19:45:17.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T19:45:17.771+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T19:45:17.773+0000] {logging_mixin.py:188} INFO - 
            INSERT INTO public.dimusertype (user_type)
            VALUES ('Lead')
            ON CONFLICT (user_type) DO NOTHING;
        
[2024-08-04T19:45:17.774+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimUserType com sucesso.
[2024-08-04T19:45:17.774+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T19:45:17.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T19:45:17.783+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=Carga_Dimensao_user_type, run_id=manual__2024-08-04T19:44:58.390721+00:00, execution_date=20240804T194458, start_date=20240804T194517, end_date=20240804T194517
[2024-08-04T19:45:17.807+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T19:45:17.822+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-04T19:45:17.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
