[2024-08-05T12:05:34.786+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T12:05:34.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T11:50:00+00:00 [queued]>
[2024-08-05T12:05:34.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T11:50:00+00:00 [queued]>
[2024-08-05T12:05:34.799+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T12:05:34.805+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_fatoemailmarketing> on 2024-08-05 11:50:00+00:00
[2024-08-05T12:05:34.808+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T12:05:34.809+0000] {standard_task_runner.py:64} INFO - Started process 149 to run task
[2024-08-05T12:05:34.809+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_fatoemailmarketing', 'scheduled__2024-08-05T11:50:00+00:00', '--job-id', '1724', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpe7w0le8k']
[2024-08-05T12:05:34.811+0000] {standard_task_runner.py:91} INFO - Job 1724: Subtask carga_fatoemailmarketing
[2024-08-05T12:05:34.838+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T11:50:00+00:00 [running]> on host c056b9e5f44a
[2024-08-05T12:05:34.875+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_fatoemailmarketing' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-05T11:50:00+00:00'
[2024-08-05T12:05:34.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T12:05:34.924+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T12:05:34.949+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T12:05:34.950+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T12:05:34.955+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_fatoemailmarketing, run_id=scheduled__2024-08-05T11:50:00+00:00, execution_date=20240805T115000, start_date=20240805T120534, end_date=20240805T120534
[2024-08-05T12:05:34.991+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T12:05:35.005+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T12:05:35.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
