[2024-08-05T00:58:27.906+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T00:58:27.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:58:14.206617+00:00 [queued]>
[2024-08-05T00:58:27.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:58:14.206617+00:00 [queued]>
[2024-08-05T00:58:27.928+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T00:58:27.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_fatoemailmarketing> on 2024-08-05 00:58:14.206617+00:00
[2024-08-05T00:58:27.945+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T00:58:27.946+0000] {standard_task_runner.py:64} INFO - Started process 229 to run task
[2024-08-05T00:58:27.947+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_fatoemailmarketing', 'manual__2024-08-05T00:58:14.206617+00:00', '--job-id', '1640', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp2a48ogy2']
[2024-08-05T00:58:27.949+0000] {standard_task_runner.py:91} INFO - Job 1640: Subtask carga_fatoemailmarketing
[2024-08-05T00:58:27.978+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_fatoemailmarketing manual__2024-08-05T00:58:14.206617+00:00 [running]> on host 59ce2ba01338
[2024-08-05T00:58:28.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_fatoemailmarketing' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T00:58:14.206617+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T00:58:14.206617+00:00'
[2024-08-05T00:58:28.033+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T00:58:28.086+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T00:58:28.130+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T00:58:28.131+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T00:58:28.137+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_fatoemailmarketing, run_id=manual__2024-08-05T00:58:14.206617+00:00, execution_date=20240805T005814, start_date=20240805T005827, end_date=20240805T005828
[2024-08-05T00:58:28.173+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T00:58:28.185+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T00:58:28.186+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
