[2024-08-01T17:09:36.197+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T17:09:36.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.create_fato_email_marketing manual__2024-08-01T17:09:27.168537+00:00 [queued]>
[2024-08-01T17:09:36.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.create_fato_email_marketing manual__2024-08-01T17:09:27.168537+00:00 [queued]>
[2024-08-01T17:09:36.248+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-01T17:09:36.265+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_fato_email_marketing> on 2024-08-01 17:09:27.168537+00:00
[2024-08-01T17:09:36.294+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=778) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-01T17:09:36.303+0000] {standard_task_runner.py:64} INFO - Started process 783 to run task
[2024-08-01T17:09:36.298+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'create_fato_email_marketing', 'manual__2024-08-01T17:09:27.168537+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp268n794p']
[2024-08-01T17:09:36.305+0000] {standard_task_runner.py:91} INFO - Job 134: Subtask create_fato_email_marketing
[2024-08-01T17:09:36.475+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.create_fato_email_marketing manual__2024-08-01T17:09:27.168537+00:00 [running]> on host e27a9ccca098
[2024-08-01T17:09:36.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='create_fato_email_marketing' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T17:09:27.168537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T17:09:27.168537+00:00'
[2024-08-01T17:09:36.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T17:09:36.787+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS FatoEmailMarketing (
                id INT PRIMARY KEY,
                id_campaign INT,
                id_company INT,
                id_user_type INT,
                "to" VARCHAR(255),
                mailer VARCHAR(255),
                subject VARCHAR(255),
                sent_at TIMESTAMP,
                opened_at TIMESTAMP,
                clicked_at TIMESTAMP,
                token VARCHAR(255),
                FOREIGN KEY (id_campaign) REFERENCES DimCampaign(id_campaign),
                FOREIGN KEY (id_company) REFERENCES DimCompany(id_company),
                FOREIGN KEY (id_user_type) REFERENCES DimUserType(id_user_type)
            );
        
[2024-08-01T17:09:36.817+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-01T17:09:36.943+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-01T17:09:37.052+0000] {sql.py:495} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS FatoEmailMarketing (
                id INT PRIMARY KEY,
                id_campaign INT,
                id_company INT,
                id_user_type INT,
                "to" VARCHAR(255),
                mailer VARCHAR(255),
                subject VARCHAR(255),
                sent_at TIMESTAMP,
                opened_at TIMESTAMP,
                clicked_at TIMESTAMP,
                token VARCHAR(255),
                FOREIGN KEY (id_campaign) REFERENCES DimCampaign(id_campaign),
                FOREIGN KEY (id_company) REFERENCES DimCompany(id_company),
                FOREIGN KEY (id_user_type) REFERENCES DimUserType(id_user_type)
            );
        , parameters: None
[2024-08-01T17:09:37.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T17:09:37.094+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "dimcampaign" does not exist

[2024-08-01T17:09:37.150+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=create_fato_email_marketing, run_id=manual__2024-08-01T17:09:27.168537+00:00, execution_date=20240801T170927, start_date=20240801T170936, end_date=20240801T170937
[2024-08-01T17:09:37.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 134 for task create_fato_email_marketing (relation "dimcampaign" does not exist
; 783)
[2024-08-01T17:09:37.226+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-01T17:09:37.324+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T17:09:37.327+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
